name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

#      - name: Copy docker-compose.yml to EC2
#        run: |
#          scp -i key.pem -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} docker-compose.yml ${{ secrets.EC2_HOST }}:~/docker-compose.yml

      - name: Deploy using Docker Compose on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} << 'EOF'
            REPO_DIR="DE-test"
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/MarkChukwuebuka/DE-test.git
            fi
          
            cd "$REPO_DIR"
            git pull origin main
          
            sudo docker compose -f docker-compose.yml up -d
          
            echo "Waiting for web service to be healthy..."
            sleep 10
          
            sudo docker compose ps
            sudo docker compose exec web python src/data_loader.py
          EOF
