name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy docker-compose.yml to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} docker-compose.yml ${{ secrets.EC2_HOST }}:~/docker-compose.yml

      - name: Deploy using Docker Compose on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} << 'EOF'
            docker pull markchukwuebuka/invoice_processor:latest
            docker compose -f ~/docker-compose.yml down
            docker compose -f ~/docker-compose.yml up -d
          EOF
